services:
  - type: web
    name: cultural-bias-analyzer
    env: python
    plan: free
    pythonVersion: 3.12.3
    buildCommand: python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app