services:
  - type: web
    name: fairy-tales-bias
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app --workers 3 --threads 2 --timeout 120
    healthCheckPath: /health
    autoDeploy: true
