services:
  - type: web
    name: fairy-tales-bias
    env: python
    plan: free
    pythonVersion: 3.12.3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
